//
//  KPCAAElementsPlanetaryOrbit.h
//  SwiftAA
//
//  Created by Cédric Foellmi on 05/07/15.
//  Licensed under the MIT License (see LICENSE file)
//

#import <Foundation/Foundation.h>

double KPCAAElementsPlanetaryOrbitMercuryMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitMercurySemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitMercuryEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitMercuryInclination(double JD);
double KPCAAElementsPlanetaryOrbitMercuryLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitMercuryLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitVenusMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitVenusSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitVenusEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitVenusInclination(double JD);
double KPCAAElementsPlanetaryOrbitVenusLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitVenusLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitEarthMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitEarthSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitEarthEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitEarthInclination(double JD);
double KPCAAElementsPlanetaryOrbitEarthLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitMarsMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitMarsSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitMarsEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitMarsInclination(double JD);
double KPCAAElementsPlanetaryOrbitMarsLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitMarsLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitJupiterMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitJupiterSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitJupiterEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitJupiterInclination(double JD);
double KPCAAElementsPlanetaryOrbitJupiterLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitJupiterLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitSaturnMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitSaturnSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitSaturnEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitSaturnInclination(double JD);
double KPCAAElementsPlanetaryOrbitSaturnLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitSaturnLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitUranusMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitUranusSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitUranusEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitUranusInclination(double JD);
double KPCAAElementsPlanetaryOrbitUranusLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitUranusLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitNeptuneMeanLongitude(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneSemimajorAxis(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneEccentricity(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneInclination(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneLongitudeAscendingNode(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneLongitudePerihelion(double JD);

double KPCAAElementsPlanetaryOrbitMercuryMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitMercuryInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitMercuryLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitMercuryLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitVenusMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitVenusInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitVenusLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitVenusLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitEarthMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitEarthInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitEarthLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitEarthLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitMarsMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitMarsInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitMarsLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitMarsLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitJupiterMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitJupiterInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitJupiterLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitJupiterLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitSaturnMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitSaturnInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitSaturnLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitSaturnLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitUranusMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitUranusInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitUranusLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitUranusLongitudePerihelionJ2000(double JD);

double KPCAAElementsPlanetaryOrbitNeptuneMeanLongitudeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneInclinationJ2000(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneLongitudeAscendingNodeJ2000(double JD);
double KPCAAElementsPlanetaryOrbitNeptuneLongitudePerihelionJ2000(double JD);


